alignment_tags/urls.py
from django.urls import path

from . import views

app_name = 'alignment_tags'

urlpatterns = [
    path('levels-and-tags/', views.LevelsAndTags.as_view(), name='levels'),
]

sr_test_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    url(r'^api/', include('alignment_tags.urls', namespace='alignment_tags')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index')
]

aligment_tags_domain/models.py
from typing import Optional
import attr
from attr.validators import optional
from enum import Enum


check_int = attr.validators.instance_of(int)
check_str = attr.validators.instance_of(str)


class DefinitionLevelTypes(Enum):
    STANDARD = 'STANDARD'
    GRADE = 'GRADE'
    LEARNING_DOMAIN = 'LEARNING_DOMAIN'


@attr.s
class DefinitionLevelType:
    name = attr.ib(validator=check_str)  # type: str
    is_internal = attr.ib(default=False)  # type: bool
    id = attr.ib(validator=optional(check_int), default=None)  # type: Optional[int]


@attr.s
class DefinitionLevel:
    """ Item of tag definition hierarchy level:
    [STANDARD|GRADE|LEARNING_DOMAIN] or non-hieararchy attr like END_GRADE
    """
    value = attr.ib(validator=check_str)  # type: str
    parent_id = attr.ib(validator=optional(check_int), default=None)  # type: Optional[int]
    id = attr.ib(default=None)  # type: Optional[int]
    type_id = attr.ib(default=None)  # type: Optional[int]


@attr.s
class Tag:
    parent_level_id = attr.ib(validator=check_int)  # type: int
    code = attr.ib()  # type: str
    description = attr.ib()  # type: description
    id = attr.ib(validator=optional(check_int), default=None)  # type: Optional[int]

    @code.validator
    def check(self, attribute, value):
        if not value:
            raise ValueError('`code` required')

alignment_tags/models.py
from django.db import models


class DefinitionLevelType(models.Model):
    name = models.CharField(max_length=512, unique=True)
    is_internal = models.BooleanField(default=False)


class DefinitionLevel(models.Model):
    type = models.ForeignKey(DefinitionLevelType, on_delete=models.CASCADE)
    value = models.CharField(max_length=512)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('value', 'parent')


class Tag(models.Model):
    parent_level = models.ForeignKey(DefinitionLevel, on_delete=models.CASCADE)
    code = models.CharField(unique=True, max_length=255)
    description = models.TextField(blank=True, null=True)

alignment_tags/views.py
from django.apps.registry import apps
from django.http import JsonResponse
from django.views.generic import View
from django import forms

from aligment_tags_domain.iservice import IAlignmentTagsService


class LevelsGetForm(forms.Form):
    parent = forms.IntegerField(required=False)


class LevelsAndTags(View):
    def get(self, *args, **kwargs):
        form = LevelsGetForm(data=self.request.GET)
        if not form.is_valid():
            return JsonResponse(data={'errors': form.errors}, status=403)

        parent_id = form.cleaned_data['parent']

        service = apps.get_app_config('alignment_tags').service  # type: IAlignmentTagsService
        return JsonResponse([o.__dict__ for o in service.get_definition_levels_and_tags(parent_id)], safe=False)

sr_test_project/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test Project</title>

    <style>
        .hidden{
            display: none;
        }
        select{
            display: block;
        }
        .tag-display{
            background-color: bisque;
        }
        #container{
            margin-left: auto;
            margin-right: auto;
            width: 50%;
            font-family: "Roboto", "Lucida Grande", "DejaVu Sans", "Bitstream Vera Sans", Verdana, Arial, sans-serif;
            font-size: 1em;
        }
        select{
            font-size: 1em;
            margin-bottom: 5px;
        }
        #tag-display{
            padding: 1em;
            min-height: 5em;
            visibility:hidden;
        }
    </style>
</head>
<body>

<div id="container">
    <div id="tag-display" class="tag-display"></div>

    <label for="select-standard" class="select-standard">Education Standard</label>
    <select id="select-standard" class="select-standard">
        <option value="">Select a Standard</option>
    </select>

    <label for="select-grade" class="select-grade hidden">Grade Level</label>
    <select id="select-grade" class="select-grade hidden">
        <option value="">Select a Grade Level</option>
    </select>

    <label for="select-domain" class="select-domain hidden">Learning Domain</label>
    <select id="select-domain" class="select-domain hidden">
        <option value="">Select a Learning Domain</option>
    </select>

    <label for="select-tag" class="select-tag hidden">Alignment Tag</label>
    <select id="select-tag" class="select-tag hidden">
        <option value="">Select an Alignment Tag</option>
    </select>
</div>

<script src="http://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script>
    let api_url = "{% url 'alignment_tags:levels' %}";

    let selectHierarchyMap = {
        "select-standard": "select-grade",
        "select-grade": "select-domain",
        "select-domain": "select-tag"
    };

    let levelTypeToSelectorMap = {
        "STANDARD": "select-standard",
        "GRADE": "select-grade",
        "LEARNING_DOMAIN": "select-domain",
        "TAG": "select-tag"
    };

    let elements = {
        "select-standard": $("#select-standard"),
        "select-grade": $("#select-grade"),
        "select-domain": $("#select-domain"),
        "select-tag": $("#select-tag"),
        "tag-display": $("#tag-display")
    };

    function hideAndClearChildrenSelects(id) {
        elements["tag-display"].text("").css("visibility", "hidden");

        while (true){
            id = selectHierarchyMap[id];

            if (id === undefined) {
                return
            }

            $('.'+id).hide();

            elements[id].find("option[value!='']").remove();
        }
    }

    function fillSelects(parent){
        $.getJSON( api_url, {"parent": parent}, function( data ) {
            $.each(data, function(idx, item) {
                let jqEl = elements[levelTypeToSelectorMap[item.type]];
                let text = (item.description ? (item.value + " - " + item.description)  : item.value);
                jqEl.append(
                    $('<option>',{ "value" : item.id, "data-value": item.value, "data-description": item.description, "data-type": item.type }).text(text));
                $("."+levelTypeToSelectorMap[item.type]).show();

            });
        });
    }

    function onChange(ev) {
        let self = this;
        let selected = $(this).find("option:selected");
        let parent = selected.val();

        hideAndClearChildrenSelects(self.id);

        if (!parent){
            return
        }

        if (selected.data("type") === "TAG"){
            let standard = elements["select-standard"].find('option:selected').text();
            let code = selected.data("value");
            let description = selected.data("description");
            let grade = elements["select-grade"].find('option:selected[value!=""]').text();
            let learning_domain = elements["select-domain"].find('option:selected[value!=""]').text();
            let html = "<strong>"+standard+"</strong><br>Code: <strong>"+code+"</strong>";

            if (grade){
                html += "<br>Grade: <strong>"+grade+"</strong>";
            }
            if (learning_domain){
                html += "<br>Learning Domain: <strong>"+learning_domain+"</strong>";
            }
            if (description) {
                html += "<br>"+description;
            }

            elements["tag-display"].html(html);
            elements["tag-display"].css("visibility", "visible");
            return
        }

        fillSelects(parent);
    }

    $(function () {
        $("select").change(onChange);
        fillSelects(null);
    });
</script>

</body>
</html>